from dataclasses import dataclass
from typing import Optional, List, Tuple, Dict
import numpy as np
from pathlib import Path


@dataclass
class EMTWaveforms:
    time_s: np.ndarray
    voltages: dict  # dict of {transformer_id: (N, 3)}
    currents: dict  # dict of {transformer_id: (N, 3)}
    event_metadata: dict
    frequency_hz: float

    @property
    def feeder_voltage_abc(self):
        return self.voltages

    @property
    def feeder_current_abc(self):
        return self.currents

    @property
    def transformer_voltage_abc(self):
        return self.voltages

    @property
    def transformer_current_abc(self):
        return self.currents


class ATPOutputReader:
    """
    Parses .pl4 output generated by ATPRunner into raw EMTWaveforms.
    Supports native binary PL4, pyatp/atp_utils binary PL4, and text PL4 formats.
    Raises ValueError with stack trace if any required file, event parameter, or waveform data is missing or invalid.
    """

    def __init__(self):
        pass

    def _parse_native_binary_pl4(self, bin_path: Path) -> Optional[np.ndarray]:
        """
        Dynamically probes record size and offset to parse binary PL4 files generated by tpbigm.
        """
        try:
            with open(bin_path, "rb") as f:
                raw = f.read()
            if len(raw) < 100:
                return None

            best_arr = None
            min_t_start = float("inf")

            # Probe channels and byte offsets (ATP groups variables in blocks of 4: t, V1, V2, V3, t, I1, I2, I3 -> 8 cols)
            for nc in [8, 7, 6, 9, 10, 12, 4]:
                rec_size = nc * 4
                for offset in range(16, min(2048, len(raw) - rec_size * 2), 4):
                    try:
                        t0 = np.frombuffer(raw[offset : offset + 4], dtype=np.float32)[0]
                        t1 = np.frombuffer(
                            raw[offset + rec_size : offset + rec_size + 4], dtype=np.float32
                        )[0]
                        if 0.0 <= t0 <= 1e-4 and 1e-6 < (t1 - t0) < 1e-2:
                            n_records = (len(raw) - offset) // rec_size
                            if n_records > 10:
                                data = np.frombuffer(
                                    raw[offset : offset + n_records * rec_size], dtype=np.float32
                                ).reshape(-1, nc)
                                t = data[:, 0]
                                if np.all(np.diff(t) >= 0):  # Monotonically non-decreasing time
                                    if t0 < min_t_start:
                                        min_t_start = t0
                                        best_arr = data
                    except Exception:
                        pass

            return best_arr
        except Exception:
            return None

    def read(self, atp_result, event, transformer_id: str = "trans1") -> EMTWaveforms:
        if atp_result is None or not hasattr(atp_result, "case_path"):
            raise ValueError(f"Invalid atp_result provided to ATPOutputReader: {atp_result}")

        if event is None:
            raise ValueError("event object must be provided to ATPOutputReader")

        if (
            hasattr(event, "event_1")
            and hasattr(event, "event_2")
            and event.event_1 is not None
            and event.event_2 is not None
        ):
            if (
                not hasattr(event.event_1, "event_type")
                or not hasattr(event.event_1, "start_time_s")
                or not hasattr(event.event_1, "duration_s")
            ):
                raise ValueError(
                    f"Event 1 in co-event missing required attributes: {event.event_1}"
                )
            if not hasattr(event.event_2, "event_type"):
                raise ValueError(
                    f"Event 2 in co-event missing required attributes: {event.event_2}"
                )
            ev_type = f"{event.event_1.event_type}_{event.event_2.event_type}"
            start_s = float(event.event_1.start_time_s)
            dur_s = float(event.event_1.duration_s)
        elif (
            hasattr(event, "event_type")
            and hasattr(event, "start_time_s")
            and hasattr(event, "duration_s")
        ):
            ev_type = str(event.event_type)
            start_s = float(event.start_time_s)
            dur_s = float(event.duration_s)
        else:
            raise ValueError(
                f"Event object missing required attributes (event_type, start_time_s, duration_s): {event}"
            )

        atp_case_path = Path(atp_result.case_path)
        freq_hz = None
        try:
            with open(atp_case_path, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    if "POWER FREQUENCY" in line:
                        parts = line.split("POWER FREQUENCY")
                        if len(parts) > 1:
                            val_str = parts[1].strip().rstrip(".")
                            freq_hz = float(val_str)
                        break
        except Exception as e:
            raise ValueError(f"Failed to read ATP circuit case file '{atp_case_path}': {e}") from e

        if freq_hz is None:
            raise ValueError(
                f"POWER FREQUENCY not found or invalid in ATP circuit case file: {atp_case_path}"
            )

        event_metadata = {
            "event_type": ev_type,
            "start_time_s": start_s,
            "duration_s": dur_s,
        }

        output_path = atp_result.case_path.with_suffix(".pl4")
        if not output_path.exists():
            raise FileNotFoundError(f"ATP .pl4 output file not found: {output_path}")

        # Check if binary PL4
        is_binary = False
        try:
            with open(output_path, "rb") as f:
                header = f.read(100)
            is_binary = b"PL4:" not in header and b"C  PL4" not in header
        except Exception as e:
            raise ValueError(f"Failed to read header from ATP .pl4 file '{output_path}': {e}") from e

        if is_binary:
            # 1. Try native binary PL4 parser
            native_data = self._parse_native_binary_pl4(output_path)
            if native_data is not None and native_data.shape[0] > 0 and native_data.shape[1] >= 7:
                t = native_data[:, 0]
                voltages = {transformer_id: native_data[:, 1:4]}
                # If 8 columns (t, v1, v2, v3, t, i1, i2, i3), currents are in cols 5:8; otherwise cols 4:7
                i_cols = slice(5, 8) if native_data.shape[1] >= 8 else slice(4, 7)
                currents = {transformer_id: native_data[:, i_cols]}
                return EMTWaveforms(t, voltages, currents, event_metadata, frequency_hz=freq_hz)

            # 2. Try external pyatp/atp_utils libraries if installed
            read_fn = None
            try:
                import pyatp
                read_fn = getattr(pyatp, "read_pl4", None)
            except ImportError:
                try:
                    import atp_utils
                    read_fn = getattr(atp_utils, "read_pl4", None)
                except ImportError:
                    read_fn = None

            if read_fn is not None:
                try:
                    dfHEAD, data, miscData = read_fn(str(output_path))
                    if data is not None and data.shape[0] > 0 and data.shape[1] >= 7:
                        target_len = data.shape[0]
                        t = data[:target_len, 0]
                        voltages = {transformer_id: data[:target_len, 1:4]}
                        i_cols = slice(5, 8) if data.shape[1] >= 8 else slice(4, 7)
                        currents = {transformer_id: data[:target_len, i_cols]}
                        return EMTWaveforms(
                            t, voltages, currents, event_metadata, frequency_hz=freq_hz
                        )
                except Exception:
                    pass

        # Text-based PL4 reader fallback
        try:
            with open(output_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = [line.strip() for line in f if line.strip()]
        except Exception as e:
            raise ValueError(f"Failed to read lines from text PL4 file '{output_path}': {e}") from e

        data_rows = []
        for line in lines:
            if not line.startswith("C") and not line.startswith("/") and not line.startswith("$") and not line.startswith("PL4:"):
                parts = line.split()
                try:
                    vals = [float(p) for p in parts]
                    if len(vals) >= 7:
                        data_rows.append(vals)
                except ValueError:
                    pass

        if len(data_rows) == 0:
            dbg_path = output_path.with_suffix(".dbg")
            dbg_content = ""
            if dbg_path.exists():
                try:
                    dbg_content = f"\n--- ATP DBG Log Output ---\n{dbg_path.read_text(errors='replace')[-2000:]}"
                except Exception:
                    pass
            lis_path = output_path.with_suffix(".lis")
            lis_content = ""
            if lis_path.exists():
                try:
                    lis_content = f"\n--- ATP LIS Log Output ---\n{lis_path.read_text(errors='replace')[-2000:]}"
                except Exception:
                    pass
            err_msg = f"ATP .pl4 file '{output_path}' contains no valid 7-column numeric waveform data rows.{dbg_content}{lis_content}"
            print(f"ERROR: {err_msg}")
            raise ValueError(err_msg)

        data_arr = np.array(data_rows)
        target_len = data_arr.shape[0]
        t = data_arr[:, 0]

        voltages = {transformer_id: data_arr[:, 1:4]}
        i_cols = slice(5, 8) if data_arr.shape[1] >= 8 else slice(4, 7)
        currents = {transformer_id: data_arr[:, i_cols]}

        return EMTWaveforms(t, voltages, currents, event_metadata, frequency_hz=freq_hz)
