from dataclasses import dataclass
import numpy as np
from pathlib import Path

@dataclass
class EMTWaveforms:
    time_s: np.ndarray
    voltages: dict  # dict of {transformer_id: (N, 3)}
    currents: dict  # dict of {transformer_id: (N, 3)}
    event_metadata: dict
    frequency_hz: float = 50.0

    @property
    def feeder_voltage_abc(self):
        return self.voltages

    @property
    def feeder_current_abc(self):
        return self.currents

    @property
    def transformer_voltage_abc(self):
        return self.voltages

    @property
    def transformer_current_abc(self):
        return self.currents


class ATPOutputReader:
    """
    Parses .pl4 output generated by ATPRunner into raw EMTWaveforms.
    Supports binary PL4 (via pyatp/atp_utils) and text PL4 formats.
    Raises ValueError with stack trace if any required file, event parameter, or waveform data is missing or invalid.
    """
    def __init__(self):
        pass

    def read(self, atp_result, event, transformer_id: str = "trans1") -> EMTWaveforms:
        if atp_result is None or not hasattr(atp_result, "case_path"):
            raise ValueError(f"Invalid atp_result provided to ATPOutputReader: {atp_result}")

        if event is None:
            raise ValueError("event object must be provided to ATPOutputReader")

        if hasattr(event, "event_1") and hasattr(event, "event_2") and event.event_1 is not None and event.event_2 is not None:
            if not hasattr(event.event_1, "event_type") or not hasattr(event.event_1, "start_time_s") or not hasattr(event.event_1, "duration_s"):
                raise ValueError(f"Event 1 in co-event missing required attributes: {event.event_1}")
            if not hasattr(event.event_2, "event_type"):
                raise ValueError(f"Event 2 in co-event missing required attributes: {event.event_2}")
            ev_type = f"{event.event_1.event_type}_{event.event_2.event_type}"
            start_s = float(event.event_1.start_time_s)
            dur_s = float(event.event_1.duration_s)
        elif hasattr(event, "event_type") and hasattr(event, "start_time_s") and hasattr(event, "duration_s"):
            ev_type = str(event.event_type)
            start_s = float(event.start_time_s)
            dur_s = float(event.duration_s)
        else:
            raise ValueError(f"Event object missing required attributes (event_type, start_time_s, duration_s): {event}")

        event_metadata = {
            "event_type": ev_type,
            "start_time_s": start_s,
            "duration_s": dur_s
        }

        output_path = atp_result.case_path.with_suffix(".pl4")
        if not output_path.exists():
            raise FileNotFoundError(f"ATP .pl4 output file not found: {output_path}")

        # Check if binary PL4
        bin_path = output_path.with_suffix(".pl4.bin")
        if not bin_path.exists() and output_path.exists():
            try:
                with open(output_path, "rb") as f:
                    header = f.read(100)
                is_binary = b"PL4:" not in header and b"C  PL4" not in header
            except Exception as e:
                raise ValueError(f"Failed to read header from ATP .pl4 file '{output_path}': {e}") from e
            if is_binary:
                bin_path = output_path

        if bin_path.exists():
            read_fn = None
            try:
                import pyatp
                read_fn = getattr(pyatp, "read_pl4", None)
            except ImportError:
                try:
                    import atp_utils
                    read_fn = getattr(atp_utils, "read_pl4", None)
                except ImportError:
                    read_fn = None

            if read_fn is not None:
                try:
                    dfHEAD, data, miscData = read_fn(str(bin_path))
                except Exception as e:
                    raise ValueError(f"Failed to parse binary PL4 file '{bin_path}': {e}") from e

                if data is None or data.shape[0] == 0 or data.shape[1] < 7:
                    raise ValueError(f"Binary PL4 file '{bin_path}' contains insufficient data columns/rows: {data.shape if data is not None else None}")

                target_len = data.shape[0]
                t = data[:target_len, 0]

                voltages = {transformer_id: data[:target_len, 1:4]}
                currents = {transformer_id: data[:target_len, 4:7]}

                return EMTWaveforms(t, voltages, currents, event_metadata, frequency_hz=50.0)

        # Text-based PL4 reader
        try:
            with open(output_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = [line.strip() for line in f if line.strip()]
        except Exception as e:
            raise ValueError(f"Failed to read lines from text PL4 file '{output_path}': {e}") from e

        data_rows = []
        for line in lines:
            if not line.startswith("C") and not line.startswith("/") and not line.startswith("$") and not line.startswith("PL4:"):
                parts = line.split()
                try:
                    vals = [float(p) for p in parts]
                    if len(vals) >= 7:
                        data_rows.append(vals)
                except ValueError:
                    pass

        if len(data_rows) == 0:
            raise ValueError(f"ATP .pl4 file '{output_path}' contains no valid 7-column numeric waveform data rows")

        data_arr = np.array(data_rows)
        target_len = data_arr.shape[0]
        t = data_arr[:, 0]

        voltages = {transformer_id: data_arr[:, 1:4]}
        currents = {transformer_id: data_arr[:, 4:7]}

        return EMTWaveforms(t, voltages, currents, event_metadata, frequency_hz=50.0)
