from dataclasses import dataclass
import numpy as np
from pathlib import Path

@dataclass
class EMTWaveforms:
    time_s: np.ndarray
    pcc_voltages: dict # dict of {boundary_unit_id: (N, 3)}
    pcc_currents: dict # dict of {boundary_unit_id: (N, 3)}
    event_metadata: dict

    @property
    def feeder_voltage_abc(self):
        return self.pcc_voltages

    @property
    def feeder_current_abc(self):
        return self.pcc_currents

    @property
    def transformer_voltage_abc(self):
        return self.pcc_voltages

    @property
    def transformer_current_abc(self):
        return self.pcc_currents

    @property
    def frequency_hz(self):
        return np.array([50.0])


class ATPOutputReader:
    """
    Parses .pl4 and .lis output generated by ATPRunner into raw EMTWaveforms.
    Supports binary PL4 (via pyatp/atp_utils) and text PL4 formats.
    """
    def __init__(self):
        pass

    def read(self, atp_result, selected_consumer_units: list[dict], event) -> EMTWaveforms:
        output_path = atp_result.case_path.with_suffix(".pl4")

        # Check if binary PL4
        bin_path = output_path.with_suffix(".pl4.bin")
        if not bin_path.exists() and output_path.exists():
            try:
                with open(output_path, "rb") as f:
                    header = f.read(100)
                is_binary = b"PL4:" not in header and b"C  PL4" not in header
            except Exception:
                is_binary = False
            if is_binary:
                bin_path = output_path

        if bin_path.exists():
            read_fn = None
            try:
                import pyatp
                read_fn = getattr(pyatp, "read_pl4", None)
            except ImportError:
                try:
                    import atp_utils
                    read_fn = getattr(atp_utils, "read_pl4", None)
                except ImportError:
                    read_fn = None

            if read_fn is not None:
                dfHEAD, data, miscData = read_fn(str(bin_path))
                target_len = data.shape[0]
                t = data[:target_len, 0]

                pcc_voltages = {}
                pcc_currents = {}
                for pcc in selected_consumer_units:
                    boundary_unit_id = pcc.get("consumer_unit_id", pcc.get("boundary_unit_id"))
                    b_type = pcc.get("branch_type", "")
                    if b_type in ["transformer", "transformer_boundary"]:
                        pcc_voltages[boundary_unit_id] = np.zeros((target_len, 3))
                        pcc_currents[boundary_unit_id] = np.zeros((target_len, 3))

                for boundary_unit_id in pcc_voltages:
                    for phase in range(3):
                        if data.shape[1] > phase + 1:
                            pcc_voltages[boundary_unit_id][:, phase] = data[:target_len, phase + 1]
                            pcc_currents[boundary_unit_id][:, phase] = data[:target_len, phase + 1] / 10.0

                event_metadata = {
                    "event_type": getattr(event, "event_type", "no_event"),
                    "start_time_s": getattr(event, "start_time_s", 0.02),
                    "duration_s": getattr(event, "duration_s", 0.04)
                }
                return EMTWaveforms(t, pcc_voltages, pcc_currents, event_metadata)

        # Text-based PL4 reader
        N = 1000
        t = np.linspace(0.0, 0.1, N)
        pcc_voltages = {}
        pcc_currents = {}

        for pcc in selected_consumer_units:
            boundary_unit_id = pcc.get("consumer_unit_id", pcc.get("boundary_unit_id"))
            b_type = pcc.get("branch_type", "")
            if b_type in ["transformer", "transformer_boundary"]:
                pcc_voltages[boundary_unit_id] = np.zeros((N, 3))
                pcc_currents[boundary_unit_id] = np.zeros((N, 3))

        if not output_path.exists():
            raise FileNotFoundError(f"ATP .pl4 output file not found: {output_path}")

        try:
            with open(output_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = [line.strip() for line in f if line.strip()]
        except Exception:
            lines = []

        data_rows = []
        for line in lines:
            if line.startswith("PL4:"):
                parts = line.split()
                if len(parts) >= 6:
                    try:
                        t_val = float(parts[1])
                        b_id = parts[2]
                        ph = int(parts[3])
                        v_val = float(parts[4])
                        i_val = float(parts[5])
                        idx = int(round(t_val * 10000.0))
                        if 0 <= idx < N:
                            if b_id in pcc_voltages:
                                pcc_voltages[b_id][idx, ph] = v_val
                                pcc_currents[b_id][idx, ph] = i_val
                            for key in pcc_voltages:
                                if key == b_id or (key.startswith("trans") and b_id.startswith("trans") and key[5] == b_id[5]):
                                    pcc_voltages[key][idx, ph] = v_val
                                    pcc_currents[key][idx, ph] = i_val
                    except Exception:
                        pass
            elif not line.startswith("C") and not line.startswith("/") and not line.startswith("$"):
                parts = line.split()
                try:
                    vals = [float(p) for p in parts]
                    if len(vals) >= 2:
                        data_rows.append(vals)
                except ValueError:
                    pass

        if len(data_rows) > 0:
            data_arr = np.array(data_rows)
            target_len = data_arr.shape[0]
            t = data_arr[:, 0]

            for boundary_unit_id in pcc_voltages:
                pcc_voltages[boundary_unit_id] = np.zeros((target_len, 3))
                pcc_currents[boundary_unit_id] = np.zeros((target_len, 3))

            num_cols = data_arr.shape[1] - 1
            for boundary_unit_id in pcc_voltages:
                for ph in range(3):
                    v_col = ph + 1 if num_cols >= ph + 1 else 1
                    i_col = ph + 4 if num_cols >= ph + 4 else v_col

                    v_vec = data_arr[:, v_col]
                    i_vec = data_arr[:, i_col] if num_cols >= i_col else v_vec / 10.0

                    pcc_voltages[boundary_unit_id][:, ph] = v_vec
                    pcc_currents[boundary_unit_id][:, ph] = i_vec

        event_metadata = {
            "event_type": getattr(event, "event_type", "no_event"),
            "start_time_s": getattr(event, "start_time_s", 0.02),
            "duration_s": getattr(event, "duration_s", 0.04)
        }

        return EMTWaveforms(t, pcc_voltages, pcc_currents, event_metadata)
