import os
import shutil
import subprocess
import uuid
from pathlib import Path
from typing import Optional, Tuple
import numpy as np

from src.transient.models import TransformerSpec, TransformerWinding, ShortCircuitTest
from src.transient.atp_runner import ATPRunner


class BCTRANGenerator:
    """
    Generates BCTRAN supporting routine input decks and executes ATP under Wine
    to extract the generated coupled transformer matrix punch file (.pch) or cards.
    Uses physical factory test specifications and vector group phase shift angles.
    """

    def __init__(self, atp_runner: Optional[ATPRunner] = None):
        self.atp_runner = atp_runner or ATPRunner()

    def generate_supporting_deck(self, transformer: TransformerSpec) -> str:
        if not transformer or not transformer.windings or not transformer.short_circuit_tests:
            raise ValueError("Invalid TransformerSpec provided to BCTRANGenerator")

        freq = float(transformer.frequency_hz)
        w_hv = transformer.windings[0]
        w_lv = transformer.windings[1]
        sc = transformer.short_circuit_tests[0]

        mva_rating = float(w_hv.rated_mva)
        kva_rating = mva_rating * 1000.0
        iex_pct = float(transformer.excitation_current_percent)

        # Enforce physical excitation loss constraint: P_fe (kW) < I_ex (kW) = (iex_pct / 100) * kva_rating
        max_valid_loss_kw = 0.5 * (iex_pct / 100.0) * kva_rating
        lex_kw = min(float(transformer.excitation_loss_kw), max_valid_loss_kw)
        if lex_kw <= 0.0:
            lex_kw = 0.25 * max_valid_loss_kw

        # Card 1: Excitation test data formatted with FORTRAN specifier (BN, I2, 7E10.2, 4I2)
        c1 = f" 2{freq:10.4f}{iex_pct:10.4f}{mva_rating:10.4f}{lex_kw:10.4f}{iex_pct:10.4f}{mva_rating:10.4f}{lex_kw:10.4f} 2 2 1 1"

        # Winding 1 (HV) card - bus prefix 'HV_A' (BCTRAN 3-phase bus node names HV_A, HV_B, HV_C)
        iconn_hv = 1 if w_hv.connection.upper() == "DELTA" else 2
        w1_bus = "HV_A  "
        w1_card = f" 1{w_hv.rated_kv:10.4f}{mva_rating:10.4f}{w_hv.phase_shift_deg:10.4f}{w1_bus}{' ' * 6}{iconn_hv:2d}"

        # Winding 2 (LV) card - bus prefix 'LV_A' (BCTRAN 3-phase bus node names LV_A, LV_B, LV_C)
        iconn_lv = 1 if w_lv.connection.upper() == "DELTA" else 2
        w2_bus = "LV_A  "
        w2_card = f" 2{w_lv.rated_kv:10.4f}{mva_rating:10.4f}{w_lv.phase_shift_deg:10.4f}{w2_bus}{' ' * 6}{iconn_lv:2d}"

        # Short circuit test card
        sc_z_pos = float(sc.z_pos_pu) * 100.0  # convert pu to %
        sc_loss_pos = float(sc.losses_pos_kw)
        sc_z_zero = float(sc.z_zero_pu if sc.z_zero_pu is not None else sc.z_pos_pu) * 100.0
        sc_loss_zero = float(sc.losses_zero_kw if sc.losses_zero_kw is not None else sc.losses_pos_kw)

        sc_card = f" 1 2{sc_loss_pos:10.4f}{sc_z_pos:10.4f}{sc_loss_zero:10.4f}{sc_z_zero:10.4f}{mva_rating:10.4f}"

        deck_lines = [
            "BEGIN NEW DATA CASE",
            "ACCESS MODULE BCTRAN",
            "$ERASE",
            c1,
            w1_card,
            w2_card,
            sc_card,
            " ",
            "$PUNCH",
            "BEGIN NEW DATA CASE",
            "BLANK",
        ]

        return "\n".join(deck_lines)

    def extract_punch_cards(self, text_content: str) -> str:
        """
        Extracts punched coupled transformer matrix cards ($VINTAGE, 1, ... USE OLD)
        from ATP PCH punch file or LIS log output generated by $PUNCH request.
        """
        if not text_content:
            raise ValueError("Empty content provided to extract_punch_cards")

        lines = text_content.splitlines()
        punch_lines = []
        capturing = False

        for line in lines:
            if "$VINTAGE, 1," in line or "$VINTAGE,1," in line:
                capturing = True
                punch_lines.append(line.rstrip())
                continue
            if capturing:
                punch_lines.append(line.rstrip())
                if "USE OLD" in line or "$VINTAGE, -1," in line:
                    if "USE OLD" not in line:
                        punch_lines.append("  USE OLD")
                    break

        if not punch_lines:
            raise ValueError(
                f"Could not find BCTRAN punch matrix block ($VINTAGE, 1, ... USE OLD) in output.\nContent tail:\n{text_content[-2000:]}"
            )

        # Filter out trailing separator markers if any
        clean_lines = []
        for line in punch_lines:
            if "End of LUNIT7" in line or "case separator" in line:
                continue
            clean_lines.append(line)

        return "\n".join(clean_lines)

    def generate(
        self, transformer: TransformerSpec, work_dir: Optional[Path] = None
    ) -> str:
        """
        Generates supporting BCTRAN case, executes ATP under Wine, and returns the
        punched coupled transformer matrix cards string (.pch).
        """
        deck = self.generate_supporting_deck(transformer)

        scratch_dir = work_dir or Path(
            f"src/simulation/bctran_scratch_{os.getpid()}_{uuid.uuid4().hex[:8]}"
        )
        scratch_dir.mkdir(parents=True, exist_ok=True)
        case_path = scratch_dir / f"bctran_{transformer.name}.ATP"

        try:
            with open(case_path, "w", encoding="utf-8") as f:
                f.write(deck)

            atp_result = self.atp_runner.run(case_path, expect_pl4=False)

            # Check for output punch file .pch or .PCH first
            pch_path = case_path.with_suffix(".pch")
            if not pch_path.exists():
                pch_path = case_path.with_suffix(".PCH")

            if pch_path.exists():
                pch_text = pch_path.read_text(errors="replace")
                try:
                    return self.extract_punch_cards(pch_text)
                except ValueError:
                    pass

            lis_path = case_path.with_suffix(".lis")
            if not lis_path.exists():
                raise FileNotFoundError(
                    f"BCTRAN log/punch output file not found at {pch_path} or {lis_path}"
                )

            lis_text = lis_path.read_text(errors="replace")
            punch_matrix = self.extract_punch_cards(lis_text)
            return punch_matrix

        finally:
            if work_dir is None and scratch_dir.exists():
                try:
                    shutil.rmtree(scratch_dir)
                except Exception:
                    pass
